const seriesDownloadLinks = {
  "Khauf": "https://linkz.mom/number/36997",
  "Kesari Chapter 2": "https://linkz.mom/number/37018",
  "Sikandar": "https://linkz.mom/number/36158",
  "The Wheel of Time": "https://linkz.mom/number/35460",
  "iHostage": "https://linkz.mom/number/36914",
  "Logout": "https://linkz.mom/number/37016",
  "Jaat": "https://linkz.mom/number/36771",
  "L2: Empuraan": "https://linkz.mom/number/36013",
  "The Glass Dome": "https://linkz.mom/number/36957",
  "Fight or Flight": "https://linkz.mom/number/36977",
  "Peter Pan’s Neverland Nightmare": "https://linkz.mom/number/36988",
  "Mere Husband Ki Biwi": "https://linkz.mom/number/34486",
  "Captain America: Brave New World": "https://linkz.mom/number/34180",
  "Daredevil: Born Again": "https://linkz.mom/number/35382",
  "The Last Of Us": "https://linkz.mom/number/12093",
  "The Divorce Insurance": "https://linkz.mom/number/36263",
  "The Last Stop in Yuma County": "https://linkz.mom/number/36948",
  "The Diamond Heist": "https://linkz.mom/number/36979",
  "La Brea": "https://linkz.mom/number/36937",
  "North of North": "https://linkz.mom/number/36881",
  "Karma": "https://linkz.mom/number/36578",
  "Daayan": "https://linkz.mom/number/36660",
  "The Gardener": "https://linkz.mom/number/36862",
  "The Bondsman": "https://linkz.mom/number/36504",
  "The Legend of Hanuman": "https://linkz.mom/number/36845",
  "Adrishyam – The Invisible Heroes": "https://linkz.mom/number/36656",
  "Bad Influence: The Dark Side of Kidfluencing": "https://linkz.mom/number/36758",
  "Black Mirror": "https://linkz.mom/number/36796",
  "[18+] Ankhiyon Se Goli Maare": "https://linkz.mom/number/36622",
  "Gone Girls: The Long Island Serial Killer": "https://linkz.mom/number/36246",
  "Chamak": "https://linkz.mom/number/36599",
  "Get Millie Black": "https://linkz.mom/number/36566",
  "Caught": "https://linkz.mom/number/35961",
  "Campus Beats": "https://linkz.mom/number/36858",
  "9 Hours": "https://linkz.mom/number/15173",
  "Pehla Pyaar – less than 1% chance": "https://linkz.mom/number/27237",
  "The Confidante": "https://linkz.mom/number/36558",
  "Lootere": "https://linkz.mom/number/20706",
  "Shaitan": "https://linkz.mom/number/7167",
  "Dayaa": "https://linkz.mom/number/36449",
  "Mansion 24": "https://linkz.mom/number/36423",
  "Sultan Of Delhi": "https://linkz.mom/number/11108",
  "Devil May Cry": "https://linkz.mom/number/36508",
  "Vadhuvu": "https://linkz.mom/number/36376",
  "The Family Man": "https://linkz.mom/number/3440",
  "Power of Paanch": "https://linkz.mom/number/33114",
  "Human": "https://linkz.mom/number/7873",
  "Athidhi": "https://linkz.mom/number/9300",
  "Myself Allen Swapan": "https://linkz.mom/number/36406",
  "The Freelancer": "https://linkz.mom/number/6170",
  "[18+] Kundi Mat Khadkao Raja": "https://linkz.mom/number/36292",
  "Kerala Crime Files": "https://linkz.mom/number/36332",
  "Mathagam": "https://linkz.mom/number/3931",
  "Aakhri Sach": "https://linkz.mom/number/4680",
  "Saas, Bahu Aur Flamingo": "https://linkz.mom/number/7293",
  "Kaala": "https://linkz.mom/number/8816",
  "Touch Me Not": "https://linkz.mom/number/36545",
  "Grahan": "https://linkz.mom/number/36270",
  "Aar Ya Paar": "https://linkz.mom/number/36229",
  "House of David": "https://linkz.mom/number/34740",
  "Pehla Chakravyuh: Chalava": "https://linkz.mom/number/36111",
  "Vadhandhi: The Fable of Velonie": "https://linkz.mom/number/15129",
  "Indu": "https://linkz.mom/number/35986",
  "[18+] B.A. Pass 2": "https://linkz.mom/number/2129",
  "The Lady’s Companion": "https://linkz.mom/number/36069",
  "Kill Dill – The Heartbreak Club": "https://linkz.mom/number/36065",
  "An Astrological Guide for Broken Hearts": "https://linkz.mom/number/35883",
  "Om Kaali Jai Kaali": "https://linkz.mom/number/36038",
  "Locked": "https://linkz.mom/number/10817",
  "[18+] B.A. Pass": "https://linkz.mom/number/2127",
  "[18+] Raat Baaki Baat Baaki": "https://linkz.mom/number/35811",
  "[18+] Chaashni": "https://linkz.mom/number/35813",
  "Khakee: The Bengal Chapter": "https://linkz.mom/number/35760",
  "Kanneda": "https://linkz.mom/number/35796",
  "The Night Manager": "https://linkz.mom/number/5908",
  "[18+] Chidiya": "https://linkz.mom/number/35656",
  "Woman Of The Dead": "https://linkz.mom/number/35704",
  "Khadaan": "https://linkz.mom/number/35599",
  "Zid Ka Khel": "https://linkz.mom/number/35408",
  "Loot Kaand": "https://linkz.mom/number/35724",
  "Rangbaaz: Darr Ki Rajneeti": "https://linkz.mom/number/4337",
  "Rangbaaz": "https://linkz.mom/number/4341",
  "Rangbaaz Phirse": "https://linkz.mom/number/4339",
  "Auto Shankar": "https://linkz.mom/number/35332",
  "The Package": "https://linkz.mom/number/35208",
  "Suzhal: The Vortex": "https://linkz.mom/number/34772",
  "The Waking of a Nation": "https://linkz.mom/number/35106",
  "Jubliee": "https://linkz.mom/number/35075",
  "840": "https://linkz.mom/number/35041",
  "[18+] Titliyaan": "https://linkz.mom/number/3241",
  "[18+] Ansh": "https://linkz.mom/number/34940",
  "Hot Wheels: Let’s Race": "https://linkz.mom/number/35037",
  "Flesh": "https://linkz.mom/number/34922",
  "Running Point": "https://linkz.mom/number/34731",
  "Love Under Construction": "https://linkz.mom/number/34787",
  "Aashram 3": "https://linkz.mom/number/34690",
  "29th February": "https://linkz.mom/number/34686",
  "[18+] Lag Ja Gale": "https://linkz.mom/number/34797",
  "Ziddi Girls": "https://linkz.mom/number/34701",
  "Aashram Chapter 2 : The Dark Side": "https://linkz.mom/number/2190",
  "Train to Busan 2: Peninsula": "https://linkz.mom/number/18894",
  "Oops! Ab Kya?": "https://linkz.mom/number/34412",
  "Dupahiya": "https://linkz.mom/number/35136",
  "@Followers": "https://linkz.mom/number/34587",
  "Faadu: A Love Story": "https://linkz.mom/number/34531",
  "Aashram": "https://linkz.mom/number/2192",
  "Crime Beat": "https://linkz.mom/number/34471",
  "[18+] Ishq Katilana": "https://linkz.mom/number/34495",
  "School Friends": "https://linkz.mom/number/34481",
  "Shringarika": "https://linkz.mom/number/32731",
  "Sacred Games": "https://linkz.mom/number/1338",
  "Ghoul": "https://linkz.mom/number/34371",
  "Pyaar Testing": "https://linkz.mom/number/34234",
  "Pyar Ka Professor": "https://linkz.mom/number/34300",
  "[18+] Balam Pichkari": "https://linkz.mom/number/34203",
  "Halala": "https://linkz.mom/number/34155",
  "Single’s Inferno": "https://linkz.mom/number/33713",
  "Bishohori": "https://linkz.mom/number/34200",
  "Bada Naam Karenge": "https://linkz.mom/number/33829",
  "Khakee: The Bihar Chapter": "https://linkz.mom/number/4499",
  "[18+] Lene Ke Dene": "https://linkz.mom/number/34060",
  "Sabrina": "https://linkz.mom/number/33955",
  "[18+] Namkeen Kisse": "https://linkz.mom/number/29894",
  "Flames": "https://linkz.mom/number/18192",
  "Selection Day": "https://linkz.mom/number/36200",
  "Kobali": "https://linkz.mom/number/33629",
  "Stranger Things": "https://linkz.mom/number/15585",
  "Jeet Ki Zid": "https://linkz.mom/number/6768",
  "Victim": "https://linkz.mom/number/33568",
  "[18+] Dekho Magar Pyar Se": "https://linkz.mom/number/33640",
  "CAT": "https://linkz.mom/number/33485",
  "Jhansi": "https://linkz.mom/number/8331",
  "[18+] Mere Angane Mein": "https://linkz.mom/number/33406",
  "Tu Zakhm Hai": "https://linkz.mom/number/33392",
  "Stay Close": "https://linkz.mom/number/33308",
  "Akkad Bakkad Rafu Chakkar": "https://linkz.mom/number/33353",
  "Personal Trainer": "https://linkz.mom/number/32733",
  "The Secrets of the Shiledars": "https://linkz.mom/number/33408",
  "Gunaah": "https://linkz.mom/number/32076",
  "The Night Agent": "https://linkz.mom/number/32982",
  "[18+] Utha Le Jaunga": "https://linkz.mom/number/32899",
  "The Roshans": "https://linkz.mom/number/32742",
  "Paatal Lok – Amazon Original": "https://linkz.mom/number/32705",
  "[18+] Mithai Wali": "https://linkz.mom/number/32721",
  "Chidiya Udd": "https://linkz.mom/number/32613",
  "Griha Laxmi": "https://linkz.mom/number/32672",
  "Dan Da Dan": "https://linkz.mom/number/32528",
  "Sa Re Ga Ma Pa": "https://linkz.mom/number/28272",
  "Black Warrant": "https://linkz.mom/number/32414",
  "Selling the City": "https://linkz.mom/number/32351",
  "Bullfight": "https://linkz.mom/number/32372",
  "[18+] Payal": "https://linkz.mom/number/32262",
  "[18+] Nurse": "https://linkz.mom/number/32129",
  "[18+] Dons and Darlings": "https://linkz.mom/number/31784",
  "Scam 1992: The Harshad Mehta Story": "https://linkz.mom/number/6562",
  "Khoj: Parchaiyo Ke Uss Paar": "https://linkz.mom/number/31766",
  "Doctors": "https://linkz.mom/number/31768",
  "Agra Affair": "https://linkz.mom/number/32311",
  "Inside Edge": "https://linkz.mom/number/31741",
  "Swipe Crime": "https://linkz.mom/number/31467",
  "Moonwalk": "https://linkz.mom/number/31461",
  "Pyramid-Scheme Ya Scam": "https://linkz.mom/number/31471",
  "Party Till I Die": "https://linkz.mom/number/31664",
  "Cubicles": "https://linkz.mom/number/31476",
  "[18+] Aah Se Aaha Tak": "https://linkz.mom/number/31402",
  "[18+] Kaanta Laga": "https://linkz.mom/number/31478",
  "Aindham Vedham": "https://linkz.mom/number/31285",
  "SSS – Sex,Secret Aur Saaya": "https://linkz.mom/number/31265",
  "Mismatched": "https://linkz.mom/number/31263",
  "Karate Girls": "https://linkz.mom/number/31251",
  "Bandish Bandits": "https://linkz.mom/number/31199",
  "Maeri": "https://linkz.mom/number/31219",
  "[18+] Dil To Baccha Hai": "https://linkz.mom/number/31078",
  "Tanaav": "https://linkz.mom/number/30939",
  "Mandaar": "https://linkz.mom/number/30691",
  "Mohrey": "https://linkz.mom/number/30955",
  "Chitta Ve": "https://linkz.mom/number/30586",
  "[18+] Paper": "https://linkz.mom/number/30595",
  "[18+] Ek Baar Aur": "https://linkz.mom/number/30684",
  "Yeh Kaali Kaali Ankhein": "https://linkz.mom/number/30438",
  "[18+] Kya Khoob Lagti Ho": "https://linkz.mom/number/30588",
  "Half Love Half Arranged": "https://linkz.mom/number/30224",
  "Freedom at Midnight": "https://linkz.mom/number/30202",
  "Paithani": "https://linkz.mom/number/30208",
  "The Magic of Shiri": "https://linkz.mom/number/30182",
  "The Penguin": "https://linkz.mom/number/28424",
  "Citadel: Honey Bunny": "https://linkz.mom/number/29930",
  "Messmate": "https://linkz.mom/number/30164",
  "[18+] Ek Deewana Tha": "https://linkz.mom/number/30127",
  "Golisoda Rising": "https://linkz.mom/number/28230",
  "Nithari Crime Report": "https://linkz.mom/number/30135",
  "Mithya": "https://linkz.mom/number/29849",
  "Reeta Sanyal": "https://linkz.mom/number/29119",
  "[18+] Haseeno Ka Inteqaam": "https://linkz.mom/number/29638",
  "1000 Babies": "https://linkz.mom/number/29154",
  "Checkmate": "https://linkz.mom/number/29425",
  "Million Dollar Listing India": "https://linkz.mom/number/29598",
  "Snakes & Ladders": "https://linkz.mom/number/29143",
  "The Devil’s Hour": "https://linkz.mom/number/29177",
  "Raat Jawaan Hai": "https://linkz.mom/number/29017",
  "Gutar Gu": "https://linkz.mom/number/29015",
  "Zindaginama": "https://linkz.mom/number/28958",
  "Jai Mahendran": "https://linkz.mom/number/29012",
  "Taaza Khabar": "https://linkz.mom/number/28661",
  "Fisaddi": "https://linkz.mom/number/29172",
  "Honeymoon Photographer": "https://linkz.mom/number/28681",
  "[18+] Utha Patak": "https://linkz.mom/number/28039",
  "Manvat Murders": "https://linkz.mom/number/28813",
  "Ishq In The Air": "https://linkz.mom/number/28439",
  "The Mystery of Moksha Island": "https://linkz.mom/number/28415",
  "Ishq Gunah": "https://linkz.mom/number/28325",
  "Gaming Insaan": "https://linkz.mom/number/29488",
  "Bench Life": "https://linkz.mom/number/28177",
  "[18+] Numbari": "https://linkz.mom/number/28045",
  "Khalbali Records": "https://linkz.mom/number/28188",
  "Call Me Bae": "https://linkz.mom/number/28021",
  "Mirzapur": "https://linkz.mom/number/27785",
  "[18+] Dil Sambhal Ja Zara": "https://linkz.mom/number/28135",
  "IC 814: The Kandahar Hijack": "https://linkz.mom/number/27746",
  "Murshid": "https://linkz.mom/number/27777",
  "Barzakh": "https://linkz.mom/number/27856",
  "Qaatil Kaun": "https://linkz.mom/number/27721",
  "[18+] Chuski": "https://linkz.mom/number/27934",
  "[18+] Raat Baaki Hai": "https://linkz.mom/number/27567",
  "Cadets": "https://linkz.mom/number/27779",
  "Angry Young Men: The Salim-Javed Story": "https://linkz.mom/number/27456",
  "[18+] Rangeen Kahaniyan": "https://linkz.mom/number/27399",
  "Shekhar Home": "https://linkz.mom/number/27263",
  "Follow Kar Lo Yaar": "https://linkz.mom/number/27550",
  "Gyaarah Gyaarah": "https://linkz.mom/number/27104",
  "Life Hill Gayi": "https://linkz.mom/number/27100",
  "Yeh Meri Family": "https://linkz.mom/number/27345",
  "Manorathangal": "https://linkz.mom/number/27339",
  "Flight Attendant": "https://linkz.mom/number/27296",
  "Naam Namak Nishan": "https://linkz.mom/number/27281",
  "Betaal": "https://linkz.mom/number/27056",
  "Commander Karan Saxena": "https://linkz.mom/number/25926",
  "[18+] Sona": "https://linkz.mom/number/27218",
  "[18+] Kissa": "https://linkz.mom/number/26929",
  "Tujhpe Main Fida": "https://linkz.mom/number/26956",
  "Bad Cop": "https://linkz.mom/number/25113",
  "[18+] Choli Ke Peeche Kya Hai": "https://linkz.mom/number/26837",
  "Bluetick": "https://linkz.mom/number/26784",
  "Brinda": "https://linkz.mom/number/26904",
  "Tribhuvan Mishra CA Topper": "https://linkz.mom/number/26346",
  "Amber Girls School": "https://linkz.mom/number/26702",
  "[18+] De Dana Dan": "https://linkz.mom/number/26671",
  "Nagendran’s Honeymoons": "https://linkz.mom/number/26401",
  "My Perfectt Husband": "https://linkz.mom/number/27337",
  "Chutney Sambar": "https://linkz.mom/number/26663",
  "Masoom Season 1": "https://linkz.mom/number/26441",
  "Pill": "https://linkz.mom/number/26079",
  "Milkshake Murders": "https://linkz.mom/number/26477",
  "Showtime": "https://linkz.mom/number/26063",
  "36 Days": "https://linkz.mom/number/26046",
  "[18+] Nafrat-E-Ishq": "https://linkz.mom/number/26316",
  "Natasha: Ek Paheli": "https://linkz.mom/number/26175",
  "Raisinghani vs Raisinghani": "https://linkz.mom/number/18139",
  "[18+] Painter Babu": "https://linkz.mom/number/26213",
  "Crimes Aaj Kal – Amazon miniTV": "https://linkz.mom/number/25740",
  "[18+] Kaun Man": "https://linkz.mom/number/25930",
  "[18+] Call Me": "https://linkz.mom/number/26077",
  "Better Call Saul": "https://linkz.mom/number/24764",
  "The Holiday": "https://linkz.mom/number/26375",
  "My Lady Jane": "https://linkz.mom/number/25444",
  "[18+] Black Coffee": "https://linkz.mom/number/25420",
  "Kota Factory": "https://linkz.mom/number/25095",
  "Yakshini": "https://linkz.mom/number/24902",
  "Boka Bakshote Bondi": "https://linkz.mom/number/25274",
  "Baahubali: Crown of Blood": "https://linkz.mom/number/23660",
  "Industry": "https://linkz.mom/number/25059",
  "[18+] Love Bite": "https://linkz.mom/number/25135",
  "[18+] Naag Vadhu": "https://linkz.mom/number/25137",
  "Baaji": "https://linkz.mom/number/25013",
  "[18+] Purani Haveli": "https://linkz.mom/number/24907",
  "Sisterhood": "https://linkz.mom/number/24884",
  "Golam Mamun": "https://linkz.mom/number/24823",
  "[18+] Dishkiyaoon": "https://linkz.mom/number/25011",
  "[18+] Kasturi": "https://linkz.mom/number/24689",
  "Gaanth Chapter 1: Jamnaa Paar": "https://linkz.mom/number/24667",
  "Gullak": "https://linkz.mom/number/24562",
  "Panchayat – Season 3": "https://linkz.mom/number/24087",
  "Illegal": "https://linkz.mom/number/24146",
  "[18+] Tota": "https://linkz.mom/number/24273",
  "Helllo Jee": "https://linkz.mom/number/24393",
  "[18+] Nau Do Gyarah": "https://linkz.mom/number/24094",
  "The Raikar Case": "https://linkz.mom/number/24156",
  "[18+] Paurashpur": "https://linkz.mom/number/23783",
  "Dom": "https://linkz.mom/number/24005",
  "Basanta Ese Geche": "https://linkz.mom/number/23964",
  "Jamnapaar": "https://linkz.mom/number/23960",
  "Lampan": "https://linkz.mom/number/23574",
  "Namacool": "https://linkz.mom/number/23654",
  "Illegal – Justice, Out of Order": "https://linkz.mom/number/3568",
  "The Last Hour": "https://linkz.mom/number/23768",
  "Panchayat": "https://linkz.mom/number/250",
  "The Takht Inc": "https://linkz.mom/number/23721",
  "Thalaimai Seyalagam": "https://linkz.mom/number/23669",
  "[18+] Estate Manager": "https://linkz.mom/number/23667",
  "[18+] Red Light": "https://linkz.mom/number/23475",
  "Paashbalish": "https://linkz.mom/number/23356",
  "Heeramandi: The Diamond Bazaar": "https://linkz.mom/number/22966",
  "The Broken News": "https://linkz.mom/number/23058",
  "[18+] Corporate": "https://linkz.mom/number/23047",
  "Chacha Vidhayak Hain Humare": "https://linkz.mom/number/22622",
  "[18+] Devil": "https://linkz.mom/number/22899",
  "Murder In Mahim": "https://linkz.mom/number/23297",
  "DIL DOSTI DILEMMA": "https://linkz.mom/number/22651",
  "Shogun": "https://linkz.mom/number/19101",
  "Ranneeti: Balakot & Beyond": "https://linkz.mom/number/22659",
  "[18+] Laal Mirch": "https://linkz.mom/number/22222",
  "[18+] Machhli": "https://linkz.mom/number/22199",
  "Tiger": "https://linkz.mom/number/22197",
  "Adv. Achinta Aich": "https://linkz.mom/number/22783",
  "Family Aaj Kal": "https://linkz.mom/number/21425",
  "Rumi": "https://linkz.mom/number/21945",
  "The Walking Dead: The Ones Who Live": "https://linkz.mom/number/21388",
  "[18+] Haveli": "https://linkz.mom/number/21572",
  "Physical: 100": "https://linkz.mom/number/20581",
  "Chhabi Biswas": "https://linkz.mom/number/21814",
  "Dadur Kirti": "https://linkz.mom/number/21266",
  "Constellation": "https://linkz.mom/number/21414",
  "Murder At Koh E Fiza": "https://linkz.mom/number/20693",
  "[18+] Game": "https://linkz.mom/number/20863",
  "[18+] Pyar Ka Bazaar Car-O-Bar": "https://linkz.mom/number/20800",
  "Plaster": "https://linkz.mom/number/20716",
  "Shehar Lakhot": "https://linkz.mom/number/13310",
  "Big Girls Don’t Cry": "https://linkz.mom/number/20191",
  "Save The Tigers": "https://linkz.mom/number/20307",
  "Maharani – 3": "https://linkz.mom/number/19712",
  "SWARAJ – Prime Video": "https://linkz.mom/number/20212",
  "[18+] Fuh se Fantasy": "https://linkz.mom/number/14114",
  "Sawab": "https://linkz.mom/number/20228",
  "Shaktirupenn…": "https://linkz.mom/number/20239",
  "Love Adhura": "https://linkz.mom/number/20140",
  "[18+] Kavita Bhabhi": "https://linkz.mom/number/20098",
  "Sunflower": "https://linkz.mom/number/19285",
  "Maamla Legal Hai": "https://linkz.mom/number/19332",
  "Badi Heroine Banti Hai": "https://linkz.mom/number/19900",
  "Chaahenge Tumhe Itnaa": "https://linkz.mom/number/19579",
  "[18+] Laila": "https://linkz.mom/number/19577",
  "Rakshak India’s Braves": "https://linkz.mom/number/18635",
  "[18+] Revenge": "https://linkz.mom/number/19334",
  "Jab Mila Tu": "https://linkz.mom/number/17081",
  "Poacher – Amazon Original": "https://linkz.mom/number/18968",
  "Love Storiyaan – Amazon Prime": "https://linkz.mom/number/18147",
  "Byomkesh – Hoichoi Original": "https://linkz.mom/number/18481",
  "Aarya": "https://linkz.mom/number/12327",
  "Ararat": "https://linkz.mom/number/18344",
  "Dillogical": "https://linkz.mom/number/18244",
  "A.I.SHA My Virtual Girlfriend": "https://linkz.mom/number/18711",
  "[18+] Chehraa": "https://linkz.mom/number/18053",
  "Miss Perfect": "https://linkz.mom/number/17276",
  "[18+] Laal Lihaaf": "https://linkz.mom/number/21186",
  "Marzi": "https://linkz.mom/number/33456",
  "[18+] Cheese Cake": "https://linkz.mom/number/17568",
  "[18+] Mishti": "https://linkz.mom/number/17844",
  "Percy Jackson and the Olympians": "https://linkz.mom/number/14316",
  "Tikit": "https://linkz.mom/number/17371",
  "Karmma Calling": "https://linkz.mom/number/16737",
  "Crushed": "https://linkz.mom/number/17819",
  "Secrets of the Buddha Relics": "https://linkz.mom/number/17204",
  "Sanctuary: A Witch’s Tale": "https://linkz.mom/number/16261",
  "36 Ghanta – KLiKK Original": "https://linkz.mom/number/17200",
  "[18+] Wafa": "https://linkz.mom/number/16815",
  "[18+] BackRoad Hustle": "https://linkz.mom/number/16446",
  "Indian Police Force – Amazon Original": "https://linkz.mom/number/16289",
  "Hustlers": "https://linkz.mom/number/16652",
  "Hrid Majhare": "https://linkz.mom/number/16492",
  "Warso": "https://linkz.mom/number/16611",
  "[18+] Devar Ji": "https://linkz.mom/number/16548",
  "Cabaret": "https://linkz.mom/number/16817",
  "Kolonko": "https://linkz.mom/number/16488",
  "Mahapaap": "https://linkz.mom/number/16486",
  "Killer Soup": "https://linkz.mom/number/15749",
  "[18+] Desi Kisse: Na Umra Ki Seema Ho": "https://linkz.mom/number/16460",
  "Echo": "https://linkz.mom/number/15626",
  "Wajah": "https://linkz.mom/number/16490",
  "Cheran’s Journey": "https://linkz.mom/number/15865",
  "Dehati Ladke": "https://linkz.mom/number/15883",
  "Koffee With Karan": "https://linkz.mom/number/12041",
  "Love Sex And Death": "https://sharedisk.me/video/QSfA6q",
  "Perilloor Premier League": "https://linkz.mom/number/15235",
  "Sinpaat": "https://linkz.mom/number/15944",
  "The Curse of Parnashavari – Hoichoi WEB-DL": "https://linkz.mom/number/15723",
  "Video Cam Scam": "https://linkz.mom/number/15787",
  "Oh My Wife": "https://linkz.mom/number/15622",
  "[18+] Bijli: Ek Rosy Ki Dastan": "https://linkz.mom/number/15270",
  "[18+] Choked": "https://linkz.mom/number/15535",
  "Raja Rani Romeo – KLiKK Original": "https://linkz.mom/number/15334",
  "Ishq Aur Desire": "https://linkz.mom/number/15331",
  "Mera Bhai": "https://linkz.mom/number/15329",
  "[18+] Main Yahan Tu Wahan": "https://linkz.mom/number/15279",
  "Catch the Ghost": "https://linkz.mom/number/15153",
  "11th Hour": "https://linkz.mom/number/14453",
  "The Inside Story": "https://linkz.mom/number/15149",
  "Jaha Bolibo Shotto Bolibo": "https://linkz.mom/number/15275",
  "What If…?": "https://linkz.mom/number/14732",
  "[18+] Besudh": "https://linkz.mom/number/14584",
  "SIN: Whispers Of Guilt": "https://linkz.mom/number/14504",
  "Taari Maari Mulakato": "https://linkz.mom/number/14506",
  "History Hunter": "https://linkz.mom/number/14679",
  "[18+] Honeymoon Suite Room No. 911": "https://linkz.mom/number/14225",
  "ImMATURE – Amazon Prime Video": "https://linkz.mom/number/14054",
  "[18+] Bidaai": "https://linkz.mom/number/14457",
  "Mission Start Ab": "https://linkz.mom/number/14350",
  "Dhootha": "https://linkz.mom/number/13388",
  "Do Not Disturb": "https://linkz.mom/number/15147",
  "Ishqyapa": "https://linkz.mom/number/13545",
  "[18+] Mastram": "https://linkz.mom/number/902",
  "Adbhut – Hoichoi WEB-DL": "https://linkz.mom/number/13859",
  "[18+] Khud Khushi": "https://linkz.mom/number/13408",
  "The Village": "https://linkz.mom/number/13164",
  "[18+] Chahat": "https://linkz.mom/number/13240",
  "[18+] Sanskari": "https://linkz.mom/number/13235",
  "Tatlubaaz": "https://linkz.mom/number/13193",
  "Slum Golf": "https://linkz.mom/number/13189",
  "Sampurna": "https://linkz.mom/number/13322",
  "[18+] Angoori": "https://linkz.mom/number/13046",
  "The Railway Men – The Untold Story Of Bhopal 1984": "https://linkz.mom/number/12912",
  "[18+] CharmSukh: Bidaai": "https://linkz.mom/number/13901",
  "[18+] Angoori – Season 1 Part 1": "https://linkz.mom/number/12825",
  "Yankee": "https://linkz.mom/number/12898",
  "[18+] The Bucket List": "https://linkz.mom/number/12962",
  "Sharey Showlo – Hoichoi WEB-DL": "https://linkz.mom/number/12823",
  "Scam 2003: The Telgi Story": "https://linkz.mom/number/12301",
  "Parnashavarir Shaap": "https://linkz.mom/number/12657",
  "Rainbow Rishta": "https://linkz.mom/number/12563",
  "P.I. Meena": "https://linkz.mom/number/12335",
  "BhootMate": "https://linkz.mom/number/12446",
  "Chhotolok": "https://linkz.mom/number/12443",
  "Loki": "https://linkz.mom/number/10572",
  "The Adventures of Lleo": "https://linkz.mom/number/12441",
  "Durgo Rawhoshyo": "https://linkz.mom/number/12438",
  "Aspirants": "https://linkz.mom/number/11914",
  "Masterpeace": "https://linkz.mom/number/11944",
  "Kaala Paani – Season 1": "https://linkz.mom/number/11397",
  "[18+] Chachi No.1": "https://linkz.mom/number/11872",
  "[18+] Dekhi Andekhi": "https://linkz.mom/number/11737",
  "Permanent Roommates – TVFPlay": "https://linkz.mom/number/11354",
  "The Stocks": "https://linkz.mom/number/11791",
  "The Walking Dead: Daryl Dixon": "https://linkz.mom/number/8171",
  "Duranga – Season 2": "https://linkz.mom/number/11903",
  "Felu Mitter Lane": "https://linkz.mom/number/11300",
  "Mumbai Diaries 26/11": "https://linkz.mom/number/10591",
  "The Changeling": "https://linkz.mom/number/9058",
  "Lupin": "https://linkz.mom/number/10523",
  "[18+] Maa Ka Naka": "https://linkz.mom/number/10956",
  "[18+] Andar Ki Baat": "https://linkz.mom/number/10799",
  "Constable Girpade": "https://linkz.mom/number/10662",
  "Choona – Netflix Original": "https://linkz.mom/number/10250",
  "Hostel Daze": "https://linkz.mom/number/10023",
  "Who-s Your Gynac": "https://linkz.mom/number/10137",
  "Charlie Chopra & The Mystery of Solang Valley": "https://linkz.mom/number/10015",
  "Dead/Alive: The Search of a Mother": "https://linkz.mom/number/9846",
  "[18+] Sabak Ishq Ka": "https://linkz.mom/number/10114",
  "Bambai Meri Jaan": "https://linkz.mom/number/8644",
  "MY3": "https://linkz.mom/number/8825",
  "Only Murders in the Building": "https://episodes.modpro.blog/archives/21892",
  "Kaisi Yeh Yaariaan": "https://linkz.mom/number/6464",
  "[18+] Bekaaboo": "https://linkz.mom/number/9746",
  "Builders": "https://linkz.mom/number/9581",
  "[18+] Palang Tod: Gaon Ki Garmi": "https://linkz.mom/number/9566",
  "Scam": "https://linkz.mom/number/9552",
  "[18+] Sex Education": "https://linkz.mom/number/6893",
  "Pustak": "https://linkz.mom/number/9321",
  "Leaked": "https://linkz.mom/number/6456",
  "BF GF WTF": "https://linkz.mom/number/7849",
  "What The Fafda": "https://linkz.mom/number/8932",
  "Screwed Up": "https://linkz.mom/number/7272",
  "[18+] Antique": "https://linkz.mom/number/7927",
  "Bhabhi Ji Gadbad Hai": "https://linkz.mom/number/7270",
  "Mr. Kolketa": "https://linkz.mom/number/7801",
  "Talaq": "https://linkz.mom/number/6808",
  "Pilkunj": "https://linkz.mom/number/6382",
  "[18+] Tadap": "https://linkz.mom/number/6206",
  "Justified: City Primeval": "https://linkz.mom/number/2777",
  "[18+] Secret Ingredient": "https://linkz.mom/number/7717",
  "Kumudini Bhavan": "https://linkz.mom/number/4817",
  "Special Ops: Lioness": "https://episodes.modpro.blog/archives/58794#clickimage",
  "Bajao": "https://linkz.mom/number/4819",
  "Taali": "https://linkz.mom/number/3656",
  "[18+] Garam Masala": "https://linkz.mom/number/4986",
  "Commando": "https://linkz.mom/number/3378",
  "My Dad the Bounty Hunter": "https://episodes.modpro.blog/archives/47949",
  "The Kashmir Files: Unreported": "https://linkz.mom/number/3461",
  "Made in Heaven": "https://linkz.mom/number/3314",
  "[18+] Aamras": "https://linkz.mom/number/3721",
  "Hum Do Teen Chaar": "https://linkz.mom/number/3662",
  "The Jengaburu Curse": "https://linkz.mom/number/3279",
  "Lady Queen Gents Parlour": "https://linkz.mom/number/8935",
  "Shohrat: A Fan Investigates": "https://linkz.mom/number/3486",
  "[18+] Chull": "https://linkz.mom/number/3463",
  "From": "https://episodes.modpro.blog/archives/52885",
  "Naruto": "https://episodes.modpro.blog/archives/36631",
  "Agochora": "https://linkz.mom/number/3600",
  "Viram": "https://linkz.mom/number/3548",
  "The Hunt for Veerappan": "https://linkz.mom/number/3101",
  "[18+] Manmaniyan": "https://linkz.mom/number/3330",
  "Postmaster": "https://linkz.mom/number/3324",
  "Backpackers": "https://linkz.mom/number/3320",
  "The Witcher – Netflix Original": "https://linkz.mom/number/2608",
  "[18+] Honey Trap Squad – Altt Original": "https://linkz.mom/number/2012",
  "[18+] Desi Kisse: Woh Din": "https://linkz.mom/number/9314",
  "Web of Make Believe Death, Lies and the Internet": "https://episodes.modpro.blog/archives/32679",
  "Half CA": "https://linkz.mom/number/2449",
  "The Witcher": "https://linkz.mom/number/2624",
  "[18+] Anari": "https://linkz.mom/number/2359",
  "Machhli": "https://linkz.mom/number/2451",
  "Kohrra – Netflix Original": "https://linkz.mom/number/1904",
  "Farzi": "https://linkz.mom/number/353",
  "Amriter Sandhane: The Banaras Chapter": "https://linkz.mom/number/2265",
  "Inspector Raghavan Files": "https://linkz.mom/number/2031",
  "[18+] Betaab Ishq": "https://linkz.mom/number/2053",
  "Calm Sutra": "https://linkz.mom/number/1944",
  "Sandeep Bhaiya": "https://linkz.mom/number/1942",
  "Court Lady": "https://episodes.modpro.blog/archives/52927",
  "Victor Lessard": "https://episodes.modpro.blog/archives/51721#clickimage",
  "Homestay Murders": "https://linkz.mom/number/1920",
  "Skymed": "https://episodes.modpro.blog/archives/34449",
  "College Romance": "https://linkz.mom/number/6484",
  "Adhura": "https://linkz.mom/number/1710",
  "Sweet Home": "https://linkz.mom/number/13480",
  "More Than Friends – Season 1": "https://episodes.modpro.blog/archives/32794",
  "Man vs. Bee": "https://episodes.modpro.blog/archives/33039#clickimage",
  "Charlie Chopra": "https://linkz.mom/number/1484",
  "Listen To Love": "https://episodes.modpro.blog/archives/32792",
  "Rain or Shine": "https://episodes.modpro.blog/archives/58017",
  "[18+] Love Guru": "https://linkz.mom/number/1757",
  "Queen": "https://episodes.modpro.blog/archives/57853#clickimage",
  "[18+] Bikau": "https://linkz.mom/number/1678",
  "Kafas": "https://linkz.mom/number/1060",
  "Mercules": "https://linkz.mom/number/1402",
  "Fantastic": "https://episodes.modpro.blog/archives/33806",
  "Indian Summers": "https://episodes.modpro.blog/archives/51402",
  "Superman and Lois": "https://episodes.modpro.blog/archives/12660",
  "God’s Favorite Idiot": "https://episodes.modpro.blog/archives/57060",
  "Brand New Cherry Flavor": "https://episodes.modpro.blog/archives/21244",
  "Gotham Knights": "https://episodes.modpro.blog/archives/50317",
  "Hush Hush": "https://linkz.mom/number/7306",
  "Mauka Ya Dhokha": "https://linkz.mom/number/1320",
  "Chloe": "https://episodes.modpro.blog/archives/33027",
  "Over Water": "https://episodes.modpro.blog/archives/45074",
  "[18+] Tohfa": "https://linkz.mom/number/1030",
  "Rana Naidu": "https://linkz.mom/number/700",
  "Koi Baat Chale": "https://linkz.mom/number/659",
  "Sarvam Shakthi Mayam": "https://linkz.mom/number/657",
  "Arnold": "https://linkz.mom/number/307",
  "[18+] Palang Tod: Siskiyaan": "https://linkz.mom/number/1065",
  "[18+] Khalish": "https://linkz.mom/number/451",
  "Jee Karda": "https://linkz.mom/number/408",
  "Pret Boys – Amazon MiniTV": "https://linkz.mom/number/1178",
  "City of Dreams": "https://linkz.mom/number/4927",
  "[18+] Tere Jaisa Yaar Kaha": "https://linkz.mom/number/449",
  "Taj: Divided by Blood": "https://linkz.mom/number/375",
  "Modern Love Chennai": "https://linkz.mom/number/428",
  "Dead Pixels": "https://linkz.mom/number/269",
  "The Marvelous Mrs. Maisel": "https://episodes.modpro.blog/archives/51556",
  "Love & Death": "https://episodes.modpro.blog/archives/53046",
  "[18+] Dream Girl": "https://linkz.mom/number/453",
  "Tomorrow, I’ll Be Someone’s Girlfriend": "https://episodes.modpro.blog/archives/45431",
  "Dahaad": "https://linkz.mom/number/8034",
  "Rabbit Hole": "https://linkz.mom/number/8453",
  "[18+] Desi Kisse: Jaanch Padtaal": "https://linkz.mom/number/463",
  "Save the Tigers": "https://linkz.mom/number/8758",
  "[18+] Devrani Jethani Aur Woh": "https://linkz.mom/number/465",
  "The Tailor – Netflix Original": "https://linkz.mom/number/9159",
  "The Mandalorian": "https://linkz.mom/number/9722",
  "Tooth Pari: When Love Bites": "https://linkz.mom/number/9198",
  "Jubilee": "https://linkz.mom/number/9824",
  "Happy Family Conditions Apply": "https://linkz.mom/number/13449",
  "IRL: In Real Love": "https://leechlinks.xyz/archives/18132",
  "Swarm – Amazon Original": "https://episodes.modpro.blog/archives/50456",
  "War Sailor": "https://episodes.modpro.blog/archives/51827",
  "United Kacche": "https://leechlinks.xyz/archives/17886",
  "Ayali": "https://leechlinks.xyz/archives/18083",
  "Virodh": "https://linkz.mom/number/507",
  "Wolf Pack": "https://episodes.modpro.blog/archives/48431",
  "Wellmania": "https://episodes.modpro.blog/archives/51484",
  "Rocket Boys": "https://linkz.mom/number/3676",
  "Misty Season 1": "https://episodes.modpro.blog/archives/51425",
  "Hunter – Tootega Nahi, Todega": "https://leechlinks.xyz/archives/17748",
  "Class of 07": "https://episodes.modpro.blog/archives/50416",
  "We Lost Our Human": "https://linkz.mom/number/684",
  "Waco: American Apocalypse": "https://episodes.modpro.blog/archives/51069",
  "Netflix You": "https://episodes.modpro.blog/archives/50001",
  "The Nevers": "https://episodes.modpro.blog/archives/18711",
  "The Test: A New Era for Australia’s Team": "https://episodes.modpro.blog/archives/46171",
  "[18+] Sex/Life": "https://episodes.modpro.blog/archives/49703",
  "Jumping Girl": "https://episodes.modpro.blog/archives/49870",
  "Ben 10: Alien Force": "https://episodes.modpro.blog/archives/28539",
  "Crimes Aaj Kal": "https://linkz.mom/number/543",
  "[18+] Mohan Chabhiwala": "https://linkz.mom/number/978",
  "Ben 10: Ultimate Alien": "https://episodes.modpro.blog/archives/28747",
  "Bad Trip": "https://hblinks.pro/archives/59052",
  "Pop Kaun?": "https://leechlinks.xyz/archives/17617",
  "Lip Service": "https://episodes.modpro.blog/archives/46949",
  "Ben 10: Omniverse": "https://episodes.modpro.blog/archives/28928#clickimage",
  "Kumite 1 Warrior Hunt": "https://linkz.mom/number/1158",
  "National Treasure: Edge Of History": "https://episodes.modpro.blog/archives/44672",
  "Class – Netflix Original": "https://linkz.mom/number/11022",
  "Adamas": "https://episodes.modpro.blog/archives/47697",
  "Jab We Matched": "https://linkz.mom/number/19135",
  "Iru Dhuruvam 2023": "https://leechlinks.xyz/archives/17134",
  "Potluck": "https://leechlinks.xyz/archives/17209",
  "Jamtara – Sabka Number Ayega": "https://linkz.mom/number/7074",
  "Jaanbaaz Hindustan Ke": "https://linkz.mom/number/19374",
  "Rafta Rafta": "https://linkz.mom/number/7962",
  "Peacemaker": "https://episodes.modpro.blog/archives/27742",
  "Playground": "https://linkz.mom/number/15227",
  "Case Closed: The Culprit Hanzawa": "https://episodes.modpro.blog/archives/47499",
  "Jehanabad – Of Love & War": "https://leechlinks.xyz/archives/16824",
  "Hunt for the Indian Mujahideen": "https://linkz.mom/number/5864",
  "Roomies": "https://linkz.mom/number/18541",
  "Cell 145: Part 1 {Karagar}": "https://linkz.mom/number/5029",
  "Gunther’s Millions": "https://episodes.modpro.blog/archives/47501",
  "Hawkeye": "https://episodes.modpro.blog/archives/26069",
  "Trial By Fire": "https://linkz.mom/number/9065",
  "Willow": "https://linkz.mom/number/6784",
  "Cinema Marte Dum Tak": "https://linkz.mom/number/14305",
  "[18+] Ratri Ke Yatri": "https://linkz.mom/number/4537",
  "Story of Things": "https://linkz.mom/number/18428",
  "With Love": "https://episodes.modpro.blog/archives/26895",
  "Kathmandu Connection": "https://linkz.mom/number/3169",
  "Vikings: Valhalla": "https://episodes.modpro.blog/archives/29268",
  "Farzi Mushaira": "https://linkz.mom/number/19355",
  "TVF Pitchers": "https://linkz.mom/number/15837",
  "The One and Only": "https://episodes.modpro.blog/archives/45584",
  "Agatha Christie’s Hjerson": "https://episodes.modpro.blog/archives/45610",
  "The Files Of Young Kindaichi": "https://episodes.modpro.blog/archives/45684",
  "Physics Wallah": "https://linkz.mom/number/7113",
  "Curiosity": "https://episodes.modpro.blog/archives/44937",
  "Shantaram": "https://episodes.modpro.blog/archives/41076",
  "Beast of Bangalore Indian Predator": "https://linkz.mom/number/1952",
  "Half Pants Full Pants": "https://linkz.mom/number/18464",
  "Salesman Of The Year": "https://linkz.mom/number/17369",
  "Hasratein": "https://linkz.mom/number/7283",
  "The Bengal Scam: Bima Kando": "https://linkz.mom/number/17418",
  "Dharavi Bank": "https://linkz.mom/number/4071",
  "The Peripheral": "https://episodes.modpro.blog/archives/41484",
  "Girls Hostel": "https://linkz.mom/number/6411",
  "Meet Cute": "https://linkz.mom/number/21350",
  "The Santa Clauses": "https://episodes.modpro.blog/archives/43045",
  "War of the Worlds": "https://episodes.modpro.blog/archives/44326",
  "Country Mafia": "https://linkz.mom/number/6717",
  "Mukhbir – The Story of a Spy": "https://linkz.mom/number/10868",
  "Breathe: Into the Shadows – Amazon Original": "https://linkz.mom/number/11529",
  "Inside Job": "https://episodes.modpro.blog/archives/24900",
  "Zootopia+": "https://episodes.modpro.blog/archives/42678",
  "[18+] Teekhi Chutney": "https://linkz.mom/number/14593",
  "[18+] Medically Yourrs": "https://linkz.mom/number/3686",
  "JL 50": "https://linkz.mom/number/17562",
  "Indian Predator": "https://linkz.mom/number/3780",
  "Tripling": "https://linkz.mom/number/7918",
  "Der Pass [Pagan Peak]": "https://linkz.mom/number/15256",
  "House of the Dragon": "https://episodes.modpro.blog/archives/37356",
  "Damaged": "https://linkz.mom/number/16182",
  "Money Mafia": "https://linkz.mom/number/11439",
  "Awakening – Bodhon": "https://linkz.mom/number/15254",
  "Karm Yuddh": "https://linkz.mom/number/8507",
  "Island of the Sea Wolves": "https://linkz.mom/number/16419",
  "Netflix Aranyak": "https://linkz.mom/number/5139",
  "Feels Like Home": "https://linkz.mom/number/18404",
  "Delhi Crime": "https://linkz.mom/number/13628",
  "The Sex Lives Of College Girls": "https://linkz.mom/number/6263",
  "Douluo Continent": "https://episodes.modpro.blog/archives/37890#clickimage",
  "Dude": "https://linkz.mom/number/15709",
  "[18+] Paying Guests": "https://linkz.mom/number/6372",
  "Shiksha Mandal": "https://linkz.mom/number/4921",
  "Roohaniyat": "https://linkz.mom/number/3187",
  "Maharani": "https://linkz.mom/number/15655",
  "Traicion": "https://linkz.mom/number/9939",
  "ImMature": "https://linkz.mom/number/14139",
  "18+ Euphoria": "https://episodes.modpro.blog/archives/7078",
  "Fabulous Lives of Bollywood Wives": "https://linkz.mom/number/2787",
  "Poles Apart": "https://linkz.mom/number/21317",
  "Murder By The Sea": "https://linkz.mom/number/4175",
  "Echoes – Netflix Original": "https://linkz.mom/number/16907",
  "ImMATURE": "https://linkz.mom/number/1392",
  "Minus One": "https://linkz.mom/number/5884",
  "Duranga": "https://linkz.mom/number/4950",
  "Tamilrockerz": "https://linkz.mom/number/16658",
  "Cyber Vaar": "https://linkz.mom/number/15010",
  "Never Have I Ever – Netflix Original WEB Series": "https://linkz.mom/number/7620",
  "The Kicks": "https://linkz.mom/number/33001",
  "Dark": "https://linkz.mom/number/16846",
  "Udan Patolas": "https://linkz.mom/number/14661",
  "The Great Weddings Of Munnes": "https://linkz.mom/number/10463",
  "For All Mankind": "https://linkz.mom/number/8974",
  "Mind the Malhotras": "https://linkz.mom/number/17751",
  "Locke & Key": "https://linkz.mom/number/2434",
  "[18+] CharmSukh: Tawa Garam": "https://linkz.mom/number/6940",
  "[18+] CharmSukh: Tauba Tauba": "https://linkz.mom/number/18242",
  "Ghar Waapsi": "https://linkz.mom/number/11471",
  "Parampara Season 2": "https://linkz.mom/number/2501",
  "Dr. Arora Season 1": "https://linkz.mom/number/4163",
  "Oggy And The Cockroaches: Next Generation – Netflix Original": "https://linkz.mom/number/6431",
  "Crash Course": "https://leechlinks.xyz/archives/13687",
  "Shoorveer": "https://linkz.mom/number/3018",
  "[18+] Indori Ishq": "https://linkz.mom/number/6390",
  "Roohaniyat Season 1": "https://linkz.mom/number/3179",
  "Parampara": "https://linkz.mom/number/2509",
  "Bard Of Blood": "https://linkz.mom/number/5839",
  "Comicstaan": "https://linkz.mom/number/4109",
  "Devotion, a Story of Love and Desire – Fidelity": "https://linkz.mom/number/17287",
  "Rebelde": "https://episodes.modpro.blog/archives/27295#clickimage",
  "Doon Kand": "https://linkz.mom/number/19994",
  "Avrodh: The Siege Within Season 2": "https://linkz.mom/number/1789",
  "[18+] Cartel": "https://linkz.mom/number/7858",
  "Miya Biwi Aur Murder": "https://linkz.mom/number/19499",
  "Tomorrow": "https://linkz.mom/number/8969",
  "Strange School Tales": "https://linkz.mom/number/5210",
  "She Season 2": "https://linkz.mom/number/9033",
  "Saas Bahu Achaar Pvt. Ltd. Season 1": "https://linkz.mom/number/17797",
  "Mahabharat Murders Season 1": "https://linkz.mom/number/1247",
  "Avrodh The Siege Within": "https://linkz.mom/number/1791",
  "Bandon Mein Tha Dum Season 1": "https://linkz.mom/number/16411",
  "Laali": "https://linkz.mom/number/1249",
  "Sudha Murtys Stories Of Wit And Magic Season 1": "https://linkz.mom/number/21874",
  "The Broken News Season 1": "https://linkz.mom/number/6962",
  "Code M": "https://linkz.mom/number/17008",
  "Crash Landing on You": "https://linkz.mom/number/5293",
  "Salt City Season 1": "https://linkz.mom/number/18342",
  "Baymax": "https://linkz.mom/number/6774",
  "Nirmal Pathak Ki Ghar Wapsi": "https://linkz.mom/number/9139",
  "Ishq Express 2022": "https://leechlinks.xyz/archives/13452",
  "Home Shanti": "https://linkz.mom/number/18420",
  "[18+] Montu Pilot": "https://linkz.mom/number/4049",
  "Dhappa": "https://linkz.mom/number/21249",
  "Welcome to Eden": "https://linkz.mom/number/16475",
  "[18+] Bubblepur": "https://linkz.mom/number/18196",
  "Never Kiss Your Best Friend": "https://linkz.mom/number/4015",
  "Legends of the Ramayana with Amish": "https://linkz.mom/number/15717",
  "Srikanta": "https://linkz.mom/number/9429",
  "London Files": "https://linkz.mom/number/15986",
  "Guilty Minds": "https://linkz.mom/number/16105",
  "Mai – Netflix Original": "https://linkz.mom/number/16590",
  "Zindagi Reset": "https://linkz.mom/number/18093",
  "WeCrashed": "https://linkz.mom/number/26305",
  "[18+] Madhushala – Mouchaak": "https://linkz.mom/number/10762",
  "Indias Ultimate Warrior": "https://linkz.mom/number/4675",
  "School 2017": "https://linkz.mom/number/4379",
  "Swaanng": "https://linkz.mom/number/18206",
  "Undekhi": "https://linkz.mom/number/2644",
  "The Test Case": "https://linkz.mom/number/2174",
  "Jugaadistan Season 1": "https://linkz.mom/number/11469",
  "The Clue Season 1": "https://linkz.mom/number/15997",
  "The Fame Game": "https://linkz.mom/number/15451",
  "Bloody Brothers Season 1": "https://leechlinks.xyz/archives/11715",
  "Couple Goals": "https://linkz.mom/number/9599",
  "[18+] Game Of The Sexes": "https://linkz.mom/number/7580",
  "[18+] Peacemaker": "https://linkz.mom/number/7517",
  "Snow Angels Season 1": "https://linkz.mom/number/18127",
  "The Great Indian Murder": "https://linkz.mom/number/14341",
  "Bhaukaal": "https://linkz.mom/number/1462",
  "The Whistleblower": "https://linkz.mom/number/18449",
  "The Outpost": "https://episodes.modpro.blog/archives/6741",
  "Zila Sangrur": "https://linkz.mom/number/1898",
  "Matsya Kaand": "https://linkz.mom/number/8319",
  "Qatil Haseenaon Ke Naam": "https://linkz.mom/number/15499",
  "Campus Diaries": "https://leechlinks.xyz/archives/11067",
  "The Innocent": "https://linkz.mom/number/10908",
  "MindHunter": "https://episodes.modpro.blog/archives/4416",
  "Mum Bhai": "https://linkz.mom/number/13945",
  "Call My Agent Bollywood": "https://linkz.mom/number/11778",
  "Special Ops 1.5: The Himmat Story": "https://linkz.mom/number/10671",
  "Appletv+ See": "https://episodes.modpro.blog/archives/942",
  "Money Heist – Netflix Original": "https://linkz.mom/number/4847",
  "Cowboy Bebop – Netflix Original": "https://linkz.mom/number/13336",
  "Candy": "https://linkz.mom/number/13652",
  "Lost In Space": "https://episodes.modpro.blog/archives/26371#clickimage",
  "Maid": "https://episodes.modpro.blog/archives/23962",
  "True Story": "https://linkz.mom/number/19192",
  "[18+] Nympho: The Lust Story": "https://linkz.mom/number/4964",
  "Hello Mini": "https://linkz.mom/number/1555",
  "Hiccups and Hookups": "https://linkz.mom/number/5742",
  "Bicchoo Ka Khel": "https://linkz.mom/number/19138",
  "Tabbar": "https://linkz.mom/number/8314",
  "Bhaukaal 2020": "https://linkz.mom/number/1460",
  "Mohmaya – Mohomaya": "https://linkz.mom/number/9419",
  "Puncch Beat": "https://linkz.mom/number/17424",
  "[18+] Orange Is the New Black – Netflix Original": "https://episodes.modpro.blog/archives/3382",
  "Tandav": "https://linkz.mom/number/6533",
  "Ek Thi Begum": "https://linkz.mom/number/18229",
  "Moho Maya": "https://linkz.mom/number/20384",
  "Dark 7 White": "https://linkz.mom/number/17981",
  "[18+] Hello Mini": "https://linkz.mom/number/1551",
  "Taish": "https://linkz.mom/number/11339",
  "Special OPS": "https://linkz.mom/number/18266",
  "Chakravyuh – An Inspector Virkar": "https://linkz.mom/number/20026",
  "Fingertip": "https://linkz.mom/number/17433",
  "She": "https://linkz.mom/number/9027",
  "Your Honor Season 2": "https://linkz.mom/number/6346",
  "Pati Patni aur Panga": "https://linkz.mom/number/3365",
  "The Forgotten Army – Azaadi ke liye": "https://linkz.mom/number/15555",
  "Afsos": "https://linkz.mom/number/1259",
  "[18+] Ek Thi Begum": "https://linkz.mom/number/18227",
  "Taqdeer": "https://linkz.mom/number/10386",
  "Ragini MMS Returns": "https://linkz.mom/number/16991",
  "A Suitable Boy": "https://linkz.mom/number/15561",
  "Breathe": "https://linkz.mom/number/5313",
  "Suits: L.A.": "https://linkz.mom/number/34580",
  "Good Bad Ugly": "https://linkz.mom/number/36776",
  "Novocaine": "https://linkz.mom/number/36739",
  "G20": "https://linkz.mom/number/36778",
  "Jack": "https://linkz.mom/number/36833",
  "Chhorii 2": "https://linkz.mom/number/36835",
  "Akaal: The Unconquered": "https://linkz.mom/number/36856",
  "Pravinkoodu Shappu": "https://linkz.mom/number/36780",
  "Chhaava": "https://linkz.mom/number/34211",
  "Court – State Vs. A Nobody": "https://linkz.mom/number/36854",
  "CrazXy": "https://linkz.mom/number/34822",
  "Sweetheart!": "https://linkz.mom/number/36841",
  "Superboys of Malegaon": "https://linkz.mom/number/34824",
  "The White Lotus": "https://linkz.mom/number/34330",
  "[18+] Emmanuelle": "https://linkz.mom/number/36860",
  "A Minecraft Movie": "https://linkz.mom/number/36664",
  "The Hunting Party": "https://linkz.mom/number/33206",
  "Black Bag": "https://linkz.mom/number/36753",
  "Robinhood": "https://linkz.mom/number/36666",
  "Gumasthan": "https://linkz.mom/number/36986",
  "Oklahoma City Bombing: American Terror": "https://linkz.mom/number/37014",
  "Paani": "https://linkz.mom/number/36975",
  "10 Truths About Love": "https://linkz.mom/number/36967",
  "A Working Man": "https://linkz.mom/number/36093",
  "Chabak – Night of Murder and Romance": "https://linkz.mom/number/36935",
  "The Dupatta Killer": "https://linkz.mom/number/36955",
  "Kingston": "https://linkz.mom/number/36916",
  "Mahadev Ka Gorakhpur": "https://linkz.mom/number/27183",
  "Perusu": "https://linkz.mom/number/36893",
  "MobLand": "https://linkz.mom/number/36224",
  "CID": "https://linkz.mom/number/31535",
  "Solo Leveling": "https://linkz.mom/number/33147",
  "Bhoothakaalam": "https://linkz.mom/number/36899",
  "The Snarling": "https://linkz.mom/number/37012",
};

export default seriesDownloadLinks;