const streamLinks = {
  "Kesari Chapter 2": "https://Smoothpre.com/embed/6ho0074lwje7",
  "Sikandar": "https://Smoothpre.com/embed/r60zc6pdnbve",
  "iHostage": "https://Smoothpre.com/embed/6b7qafm552wi",
  "L2: Empuraan": "https://Smoothpre.com/embed/v6djjnksn77d",
  "Jaat": "https://Smoothpre.com/embed/caczrxwb8b67",
  "Fight or Flight": "https://Smoothpre.com/embed/jtj1tnkrmvw2",
  "Peter Pan’s Neverland Nightmare": "https://Smoothpre.com/embed/1sabqz7ief4o",
  "Mere Husband Ki Biwi": "https://Smoothpre.com/embed/1btp3w3ooilq",
  "Logout": "https://Smoothpre.com/embed/zfz093qesau7",
  "Captain America: Brave New World": "https://Smoothpre.com/embed/d0dnrsu8zxfm",
  "Good Bad Ugly": "https://Smoothpre.com/embed/derdkuz5ce2s",
  "The Last Stop in Yuma County": "https://Smoothpre.com/embed/g79zkfzackw9",
  "Novocaine": "https://Smoothpre.com/embed/s54566mr291f",
  "Akaal: The Unconquered": "https://Smoothpre.com/embed/1d6ikuj8m250",
  "Jack": "https://Smoothpre.com/embed/lgqhd9y685je",
  "Chhorii 2": "https://Smoothpre.com/embed/pef0bvjooaik",
  "Court – State Vs. A Nobody": "https://Smoothpre.com/embed/5vlovg03dvqk",
  "[18+] Emmanuelle": "https://Smoothpre.com/embed/fgp44qg217f3",
  "Chhaava": "https://Smoothpre.com/embed/yytbecrzf3ep",
  "Pravinkoodu Shappu": "https://Smoothpre.com/embed/rczleyjq6sv0",
  "G20": "https://Smoothpre.com/embed/88o9hxrk5p22",
  "CrazXy": "https://Smoothpre.com/embed/vbx6f35utzz1",
  "Superboys of Malegaon": "https://Smoothpre.com/embed/tka43qcg0nvg",
  "Sweetheart!": "https://Smoothpre.com/embed/gblreb518n32",
  "A Minecraft Movie": "https://Smoothpre.com/embed/fy5yf7ph9laz",
  "Black Bag": "https://Smoothpre.com/embed/qujt0dzmf0vw",
  "Robinhood": "https://Smoothpre.com/embed/lh57xx7jqdad",
  "Gumasthan": "https://Smoothpre.com/embed/as7xw1lqak5o",
  "Oklahoma City Bombing: American Terror": "https://Smoothpre.com/embed/5v8boada7m1s",
  "10 Truths About Love": "https://Smoothpre.com/embed/59q5f8xpjiad",
  "A Working Man": "https://Smoothpre.com/embed/cl7duw559efc",
  "Chabak – Night of Murder and Romance": "https://Smoothpre.com/embed/keji6ze7f4jt",
  "Paani": "https://Smoothpre.com/embed/fl4du2jv2kp1",
  "The Dupatta Killer": "https://Smoothpre.com/embed/6u3wysimkmsc",
  "Kingston": "https://Smoothpre.com/embed/3n790ra9mvau",
  "Mahadev Ka Gorakhpur": "https://Smoothpre.com/embed/sq5l3lvfan1m",
  "Perusu": "https://Smoothpre.com/embed/4pr5nz1r0cxz",
  "Bhoothakaalam": "https://Smoothpre.com/embed/qscz3a635e8r",
  "The Snarling": "https://Smoothpre.com/embed/dqe1ievle8g0",
  "Sky Sharks": "https://Smoothpre.com/embed/ryr8d7najgg8",
  "Tornado Warning": "https://Smoothpre.com/embed/vj07jqnf2y73",
  "Wicked Little Letters": "https://Smoothpre.com/embed/amaumx3dmvum",
  "Pintu Ki Pappi": "https://Smoothpre.com/embed/5djg8xtoaz53",
  "Rule of the Game: Manhut": "https://Smoothpre.com/embed/1gf7wokpcve9",
  "Chhorii": "https://Smoothpre.com/embed/ku3lij36ihrj",
  "Piece by Piece": "https://Smoothpre.com/embed/y3hf42z81fel",
  "Daayan": "https://Smoothpre.com/embed/bw135bvcldeg",
  "Hoshiar Singh": "https://Smoothpre.com/embed/x9o6xusjh4ab",
  "Hitmen": "https://Smoothpre.com/embed/y3po7xjd67hn",
  "High Plains Invaders": "https://Smoothpre.com/embed/gmvqho7hxs7e",
  "Connect": "https://Smoothpre.com/embed/k4s5g7cnnz4j",
  "Hara Chura": "https://Smoothpre.com/embed/4dilmaq67w7u",
  "FCUK: Father Chitti Umaa Kaarthik": "https://Smoothpre.com/embed/4id7hc9prcg5",
  "Terrifier 2": "https://Smoothpre.com/embed/kkuc0t74xikv",
  "The Royal Hotel": "https://Smoothpre.com/embed/ha0e5d0ea0jp",
  "Jules": "https://Smoothpre.com/embed/6n1hawx1br35",
  "Grand Isle": "https://Smoothpre.com/embed/uttk5cz7yv20",
  "Love on Trend": "https://Smoothpre.com/embed/ukk5oo8d1tlz",
  "What Happens Later": "https://Smoothpre.com/embed/kevjz1vx3bx9",
  "Pacific Rim 2: Uprising": "https://Smoothpre.com/embed/crdyerj4aien",
  "14 Days: Girlfriend Intlo": "https://Smoothpre.com/embed/alg8y9irwzlc",
  "Pacific Rim": "https://Smoothpre.com/embed/nyk5gzlfwkh2",
  "Bully Bad Guys": "https://Smoothpre.com/embed/8i56d21zzif4",
  "River of Blood": "https://Smoothpre.com/embed/ubi2m95kqj1u",
  "Forbidden Fairytale": "https://Smoothpre.com/embed/9i0d80fzzuzz",
  "A Dog’s Way Home": "https://Smoothpre.com/embed/hu95jyhb1gea",
  "HIT: The First Case": "https://Smoothpre.com/embed/4i172nou1vbq",
  "Kurup": "https://Smoothpre.com/embed/14qjcpu5xtpv",
  "12 Mighty Orphans": "https://Smoothpre.com/embed/yghuvmne96d3",
  "Terrifier 3": "https://Smoothpre.com/embed/e12fqrxfmr4v",
  "Upon the Magic Roads": "https://Smoothpre.com/embed/9y0rgeotpdds",
  "House of Darkness": "https://Smoothpre.com/embed/ei7z2zrv3m76",
  "Vekh Baraatan Challiyan": "https://Smoothpre.com/embed/013xbaz9904i",
  "Aladdin": "https://Smoothpre.com/embed/qglb1426yz4x",
  "Test": "https://Smoothpre.com/embed/szqienaspv80",
  "[18+] Ankhiyon Se Goli Maare": "https://Smoothpre.com/embed/my3ielj75hys",
  "Risen": "https://Smoothpre.com/embed/5kff2afbing3",
  "Tantra": "https://Smoothpre.com/embed/a6ftedtgbndw",
  "Furlow": "https://Smoothpre.com/embed/2egnh90tmh72",
};

export default streamLinks;