const movieDownloadLinks = {
  "Jaat": "https://new17.gdtot.dad/file/3142059253",
  "Good Bad Ugly": "https://new17.gdtot.dad/file/2876423105",
  "Novocaine": "https://new17.gdtot.dad/file/2300787791",
  "G20": "https://new17.gdtot.dad/file/1708309879",
  "Court – State Vs. A Nobody": "https://new17.gdtot.dad/file/2172823704",
  "Jack": "https://new17.gdtot.dad/file/2725890986",
  "Chhorii 2": "https://new17.gdtot.dad/file/2832672471",
  "Akaal: The Unconquered": "https://new17.gdtot.dad/file/2405122977",
  "Pravinkoodu Shappu": "https://new17.gdtot.dad/file/3204301193",
  "[18+] Emmanuelle": "https://new17.gdtot.dad/file/2563128375",
  "Chhaava": "https://new17.gdtot.dad/file/2954494924",
  "CrazXy": "https://new17.gdtot.dad/file/1952564968",
  "Sweetheart!": "https://new17.gdtot.dad/file/3037340633",
  "Superboys of Malegaon": "https://new17.gdtot.dad/file/2707330443",
  "A Minecraft Movie": "https://new17.gdtot.dad/file/1757545927",
  "Black Bag": "https://new17.gdtot.dad/file/1912858139",
  "Sikandar": "https://new6.gdflix.dad/file/jFpyA44aIW",
  "Robinhood": "https://new17.gdtot.dad/file/1353390481",
  "L2: Empuraan": "https://new6.gdflix.dad/file/IeUe8W1WPQ",
  "Perusu": "https://new17.gdtot.dad/file/2313952825",
  "Bhoothakaalam": "https://new17.gdtot.dad/file/1926665608",
  "Wicked Little Letters": "https://new17.gdtot.dad/file/2123372565",
  "Rule of the Game: Manhut": "https://new17.gdtot.dad/file/2144729558",
  "Chhorii": "https://new17.gdtot.dad/file/2247752484",
  "Piece by Piece": "https://new17.gdtot.dad/file/1948390514",
  "Daayan": "https://new17.gdtot.dad/file/2854238057",
  "Hoshiar Singh": "https://new17.gdtot.dad/file/2470904810",
  "Hitmen": "https://new17.gdtot.dad/file/2462508629",
  "FCUK: Father Chitti Umaa Kaarthik": "https://new17.gdtot.dad/file/3581832515",
  "Hara Chura": "https://new17.gdtot.dad/file/1074034269",
  "High Plains Invaders": "https://new17.gdtot.dad/file/1889700353",
  "Connect": "https://new17.gdtot.dad/file/2148595591",
  "Terrifier 2": "https://new17.gdtot.dad/file/3100507051",
  "The Royal Hotel": "https://new17.gdtot.dad/file/1163872098",
  "Grand Isle": "https://new17.gdtot.dad/file/1788463196",
  "Jules": "https://new17.gdtot.dad/file/1870681424",
  "Campus Beats": "https://new17.gdtot.dad/file/13046832993",
  "Love on Trend": "https://new17.gdtot.dad/file/1333796213",
  "What Happens Later": "https://new17.gdtot.dad/file/2239516639",
  "14 Days: Girlfriend Intlo": "https://new17.gdtot.dad/file/1510515327",
  "Pacific Rim 2: Uprising": "https://new17.gdtot.dad/file/3095916080",
  "Pacific Rim": "https://new17.gdtot.dad/file/3921546856",
  "Bad Influence: The Dark Side of Kidfluencing": "https://new17.gdtot.dad/file/3157832989",
  "Bully Bad Guys": "https://new17.gdtot.dad/file/2110623992",
  "River of Blood": "https://new17.gdtot.dad/file/2110030199",
  "Forbidden Fairytale": "https://new17.gdtot.dad/file/2299373740",
  "HIT: The First Case": "https://new17.gdtot.dad/file/1871204702",
  "A Dog’s Way Home": "https://new17.gdtot.dad/file/1793200844",
  "Murmur": "https://new17.gdtot.dad/file/2074649643",
  "Kurup": "https://new17.gdtot.dad/file/3076506058",
  "12 Mighty Orphans": "https://new17.gdtot.dad/file/2274281860",
  "Terrifier 3": "https://new17.gdtot.dad/file/3610949680",
  "Upon the Magic Roads": "https://new17.gdtot.dad/file/2013199950",
  "Aladdin": "https://new17.gdtot.dad/file/2470174938",
  "Moving On": "https://new17.gdtot.dad/file/1640206111",
  "House of Darkness": "https://new17.gdtot.dad/file/2349907401",
  "Vekh Baraatan Challiyan": "https://new17.gdtot.dad/file/2455009869",
  "She Came to Me": "https://new17.gdtot.dad/file/2045818829",
  "Test": "https://new17.gdtot.dad/file/2225037068",
  "Endless Rain": "https://new17.gdtot.dad/file/2419901420",
  "Risen": "https://new17.gdtot.dad/file/2423706167",
  "[18+] Ankhiyon Se Goli Maare": "https://new17.gdtot.dad/file/1614749768",
  "Furlow": "https://new17.gdtot.dad/file/2661506119",
  "Tantra": "https://new17.gdtot.dad/file/1940603765",
  "Banger": "https://new17.gdtot.dad/file/1308123942",
  "Kotee": "https://new17.gdtot.dad/file/3698016684",
  "Holland": "https://new6.gdflix.dad/file/EegInvdBBv",
  "The Brutalist": "https://new17.gdtot.dad/file/4257479345",
  "Cadaver": "https://new17.gdtot.dad/file/5032691985",
  "Yugi – Adrishyam": "https://new17.gdtot.dad/file/2585974942",
  "The Exorcists": "https://new17.gdtot.dad/file/1757106800",
  "Nuchwana": "https://new17.gdtot.dad/file/990428300",
  "Rishte Naate": "https://new17.gdtot.dad/file/2397073470",
  "Vascodagama The Evolution": "https://new17.gdtot.dad/file/2703250634",
  "Mad Square": "https://new6.gdflix.dad/file/6y7RNOkqZQ",
  "Vijayanand": "https://new17.gdtot.dad/file/3334825209",
  "Kannur Squad": "https://new17.gdtot.dad/file/4315307039",
  "IB 71": "https://new17.gdtot.dad/file/4116843401",
  "Garadi": "https://new6.gdflix.dad/file/WBj47V6R2H",
  "The Book of Clarence": "https://new17.gdtot.dad/file/2488870574",
  "Soppana Sundari": "https://new17.gdtot.dad/file/3091721479",
  "Taron Paar": "https://new17.gdtot.dad/file/2195534252",
  "The Durga Mehta Case": "https://new17.gdtot.dad/file/2735757864",
  "Carjackers": "https://new17.gdtot.dad/file/2113238443",
  "Operation: Endgame": "https://new6.gdflix.dad/file/R2lo8rCqyR",
  "Myself Allen Swapan": "https://new17.gdtot.dad/file/9599504402",
  "Mad": "https://gdflix-dad.cdn.ampproject.org/c/s/gdflix.dad/file/Fh52CTrtlz",
  "Maa Ki Mamta": "https://gdflix-dad.cdn.ampproject.org/c/s/gdflix.dad/file/JFB7yqnZ9K",
  "A Working Man": "https://new6.gdflix.dad/file/hvaMtEQG1e",
  "[18+] Kundi Mat Khadkao Raja": "https://new6.gdflix.dad/file/cheXZsR9dj",
  "Love Ni Bhavai": "https://gdflix-dad.cdn.ampproject.org/c/s/gdflix.dad/file/bATButIXB3",
  "The Invitation": "https://gdflix-dad.cdn.ampproject.org/c/s/gdflix.dad/file/qWHD6L2hMB",
  "Radha": "https://new6.gdflix.dad/file/Ti0whZTXzb",
  "The Toys": "https://gdflix-dad.cdn.ampproject.org/c/s/gdflix.dad/file/zOOxeGR0Md",
  "Majnu": "https://new6.gdflix.dad/file/zbCBFRB7e9",
  "The Darjeeling Limited": "https://new6.gdflix.dad/file/WeWE3s9iTp",
  "Qismat 2": "https://gdflix-dad.cdn.ampproject.org/c/s/gdflix.dad/file/xyCRF0RLvm",
  "Qismat": "https://new6.gdflix.dad/file/WhjS7bb9Co",
  "Mara": "https://new6.gdflix.dad/file/12hsCuluVS",
  "Captain": "https://gdflix-dad.cdn.ampproject.org/c/s/gdflix.dad/file/SvkChrk5qU",
  "Death Proof": "https://gdflix-dad.cdn.ampproject.org/c/s/gdflix.dad/file/mwbowZIRRx",
  "O2": "https://gdflix-dad.cdn.ampproject.org/c/s/gdflix.dad/file/YLLFDnOZ5O",
  "The Hobbit: The Battle of the Five Armies": "https://new6.gdflix.dad/file/IeArhM3kYF",
  "The Hobbit: The Desolation of Smaug": "https://gdflix-dad.cdn.ampproject.org/c/s/gdflix.dad/file/t1yo7Ru4jc",
  "The Hobbit: An Unexpected Journey": "https://gdflix-dad.cdn.ampproject.org/c/s/gdflix.dad/file/g3izr4kykw",
  "Freaky": "https://gdflix-dad.cdn.ampproject.org/c/s/gdflix.dad/file/EJmSOhY1hF",
  "Holiday: A Soldier Is Never Off Duty": "https://gdflix-dad.cdn.ampproject.org/c/s/gdflix.dad/file/gmG9Ywh28E",
  "Barot House": "https://gdflix-dad.cdn.ampproject.org/c/s/gdflix.dad/file/WLVufB4H8b",
  "Mittran Da Challeya Truck Ni": "https://gdflix-dad.cdn.ampproject.org/c/s/gdflix.dad/file/QyJkNDK76d",
  "Bigil": "https://new6.gdflix.dad/file/3rsTF7aZp9",
  "Challe Yaar Coachella": "https://gdflix-dad.cdn.ampproject.org/c/s/gdflix.dad/file/eyDyIzpfva",
  "The Great Mouse Detective": "https://gdflix-dad.cdn.ampproject.org/c/s/gdflix.dad/file/T21vIw55BP",
  "Hindi Medium": "https://gdflix-dad.cdn.ampproject.org/c/s/gdflix.dad/file/p8TnVvndT1",
  "Eight: The Power of Shani": "https://gdflix-dad.cdn.ampproject.org/c/s/gdflix.dad/file/ehYsr4Rw3C",
  "Naam Shabana": "https://new6.gdflix.dad/file/0KJq4aASIE",
  "Mr. Kabaadi": "https://gdflix-dad.cdn.ampproject.org/c/s/gdflix.dad/file/FgPr3NgYEZ",
  "Mitron": "https://gdflix-dad.cdn.ampproject.org/c/s/gdflix.dad/file/KDga3IApZ9",
  "Mubarakan": "https://gdflix-dad.cdn.ampproject.org/c/s/gdflix.dad/file/yQNkWO6dzP",
  "Pataakha": "https://gdflix-dad.cdn.ampproject.org/c/s/gdflix.dad/file/QRn4W4ddPe",
  "Muskurahatein": "https://gdflix-dad.cdn.ampproject.org/c/s/gdflix.dad/file/S1UIEbXiX7",
  "Panchlait": "https://new6.gdflix.dad/file/MHKOXNUxIT",
  "Mohalla Assi": "https://gdflix-dad.cdn.ampproject.org/c/s/gdflix.dad/file/ocBdA9WIwT",
  "Phullu": "https://gdflix-dad.cdn.ampproject.org/c/s/gdflix.dad/file/OykJCQGuvx",
  "Phillauri": "https://gdflix-dad.cdn.ampproject.org/c/s/gdflix.dad/file/XFxhlr0yEY",
  "Nirdosh": "https://new6.gdflix.dad/file/Php8sUkH0n",
  "Narayan": "https://gdflix-dad.cdn.ampproject.org/c/s/gdflix.dad/file/ZfGsUfe3Kw",
  "Jeena Isi Ka Naam Hai": "https://gdflix-dad.cdn.ampproject.org/c/s/gdflix.dad/file/shftwDwYlH",
  "Munna Michael": "https://new6.gdflix.dad/file/mln51vZTh7",
  "Na Ghar Ke Na Ghaat Ke": "https://new6.gdflix.dad/file/WGHv0JZFa7",
  "Patel Ki Punjabi Shaadi": "https://new6.gdflix.dad/file/IKgJd3p9gz",
  "Noor": "https://new6.gdflix.dad/file/ZZ1gMyxvKP",
  "Irada": "https://new6.gdflix.dad/file/RqVcRydxPo",
  "Crazy Cukkad Family": "https://gdflix-dad.cdn.ampproject.org/c/s/gdflix.dad/file/gg7XC6Qsc5",
  "The Diplomat": "https://new17.gdtot.dad/file/2471331200",
  "Ittefaq": "https://new6.gdflix.dad/file/qKbrzH88wE",
  "AINBO: Spirit of the Amazon": "https://gdflix-dad.cdn.ampproject.org/c/s/gdflix.dad/file/wYNXfoJEON",
  "Pehla Chakravyuh: Chalava": "https://new6.gdflix.dad/file/RHVacV6Ozm",
  "Loveyapa": "https://new17.gdtot.dad/file/3388875186",
  "Spyder": "https://new6.gdflix.dad/file/f1hHqi3G6s",
  "Kaafir": "https://new17.gdtot.dad/file/3072035328",
  "Mufasa: The Lion King": "https://new6.gdflix.dad/file/hFoCDNB5lY",
  "Little Miss Rawther": "https://new6.gdflix.dad/file/LR1BtV3swR",
  "Kill Dill – The Heartbreak Club": "https://new6.gdflix.dad/file/oIBHwQRUnu",
  "Identity": "https://new17.gdtot.dad/file/3353747395",
  "Zakir Khan: Delulu Express – Comedy Special": "https://new6.gdflix.dad/file/52RL1ztpeS",
  "Jalsa": "https://new6.gdflix.dad/file/7gtkNNinjS",
  "Vadhandhi: The Fable of Velonie": "https://new6.gdflix.dad/file/noRJkvokr9",
  "Doctor": "https://new6.gdflix.dad/file/P3HfTZCZhZ",
  "Don": "https://new6.gdflix.dad/file/SOAJLDKgxf",
  "[18+] B.A. Pass 3": "https://new6.gdflix.dad/file/iromC4geCd",
  "[18+] B.A. Pass 2": "https://new6.gdflix.dad/file/BwGYuNujpL",
  "[18+] B.A. Pass": "https://new6.gdflix.dad/file/HiH7RtC6iN",
  "Aghathiyaa": "https://new6.gdflix.dad/file/yNblpoPAxO",
  "Bol Bachchan": "https://new6.gdflix.dad/file/tGz7CYFUTq",
  "Inspector Vijay – Kavacham": "https://new6.gdflix.dad/file/Rzj5WcLqsf",
  "Gemini Man": "https://new6.gdflix.dad/file/EhKItLyDZd",
  "Drive Hard": "https://new6.gdflix.dad/file/uiLgsBKmzL",
  "The Babysitters": "https://new6.gdflix.dad/file/rd6O8auJci",
  "706": "https://new6.gdflix.dad/file/5RooMf5Ggg",
  "Indu": "https://new6.gdflix.dad/file/ik3aRCVlI9",
  "Star": "https://new6.gdflix.dad/file/DJJU1Q3TjQ",
  "Om Kaali Jai Kaali": "https://new6.gdflix.dad/file/viJEN62Y4u",
  "Viduthalai: Part 2": "https://new6.gdflix.dad/file/ptMLPVF4ui",
  "Dragon": "https://new6.gdflix.dad/file/uoSRgb8hJu",
  "Hit Man": "https://new6.gdflix.dad/file/3mj5Mkmf46",
  "Den of Thieves 2: Pantera": "https://new6.gdflix.dad/file/PwwEmli0eE",
  "The Life List": "https://new6.gdflix.dad/file/Svhu9apz2O",
  "Locked": "https://new6.gdflix.dad/file/rYg4ijvXFS",
  "Pintu Ki Pappi": "https://new6.gdflix.dad/file/HLiwtHGSr7",
  "[18+] Parthenope": "https://new6.gdflix.dad/file/crLMOIBjzI",
  "Killers": "https://gdflix-dad.cdn.ampproject.org/c/s/gdflix.dad/file/JmDwQcONQW",
  "Premika": "https://new6.gdflix.dad/file/gdpQkAgc0t",
  "Con Mum": "https://new6.gdflix.dad/file/1IskbNcPvt",
  "Den of Thieves": "https://new6.gdflix.dad/file/lhWP3EleZ3",
  "Sliver": "https://new6.gdflix.dad/file/RE6WlXZ8Zs",
  "Purushothamudu": "https://new6.gdflix.dad/file/osBVi1U8dR",
  "[18+] Trauma": "https://new6.gdflix.dad/file/T40lRYIB4y",
  "Life Mein Twist – Manasuku Nachindi": "https://new6.gdflix.dad/file/Rzj5WcLqsf",
  "Asli Fighter – Okka Ammayi Thappa": "https://gdflix-dad.cdn.ampproject.org/c/s/gdflix.dad/file/z5YfVsLnzu",
  "Makkhi – Eega": "https://gdflix-dad.cdn.ampproject.org/c/s/gdflix.dad/file/d07pMKi59N",
  "Manjhi: The Mountain Man": "https://gdflix-dad.cdn.ampproject.org/c/s/gdflix.dad/file/2srSPes4TG",
  "Daitya": "https://new6.gdflix.dad/file/QRGMrkmAp0",
  "Police Story – Anjaam Pathiraa": "https://gdflix-dad.cdn.ampproject.org/c/s/gdflix.dad/file/BFNCKyhwa1",
  "Yeh Hai Zindagi – Yevade Subramanyam": "https://gdflix-dad.cdn.ampproject.org/c/s/gdflix.dad/file/oMbXDjOAfP",
  "Apne": "https://gdflix-dad.cdn.ampproject.org/c/s/gdflix.dad/file/jGGmcH39Pf",
  "Guntur Talkies": "https://gdflix-dad.cdn.ampproject.org/c/s/gdflix.dad/file/CQdyKxyAOu",
  "Blush": "https://gdflix-dad.cdn.ampproject.org/c/s/gdflix.dad/file/Rt1cYHunoD",
  "Treasure Planet": "https://gdflix-dad.cdn.ampproject.org/c/s/gdflix.dad/file/8k2iPx9w88",
  "Revelations": "https://new6.gdflix.dad/file/cQJjYuHtAm",
  "[18+] Chaashni": "https://new6.gdflix.dad/file/gYk5dshcGp",
  "[18+] Raat Baaki Baat Baaki": "https://new6.gdflix.dad/file/1bcK2psCKS",
  "The Bannen Way": "https://gdflix-dad.cdn.ampproject.org/c/s/gdflix.dad/file/8vL95V0IR4",
  "Indrani: Epic-1 Dharam vs Karam": "https://gdflix-dad.cdn.ampproject.org/c/s/gdflix.dad/file/4uBZTFiRxi",
  "Madras Cafe": "https://gdflix-dad.cdn.ampproject.org/c/s/gdflix.dad/file/JCmafYKysq",
  "Muzaffarnagar: The Burning Love": "https://gdflix-dad.cdn.ampproject.org/c/s/gdflix.dad/file/wYhggKyZBD",
  "Screamers: The Hunting": "https://gdflix-dad.cdn.ampproject.org/c/s/gdflix.dad/file/P2iOMUefmh",
  "Baida": "https://gdflix-dad.cdn.ampproject.org/c/s/gdflix.dad/file/IcCVvG9g1n",
  "Khakee: The Bengal Chapter": "https://new6.gdflix.dad/file/DxHHyfWWtR",
  "Little Siberia": "https://gdflix-dad.cdn.ampproject.org/c/s/gdflix.dad/file/zkwglN6Z8p",
  "Wanted": "https://new6.gdflix.dad/file/vviqEtPbq8",
  "Maatr": "https://gdflix-dad.cdn.ampproject.org/c/s/gdflix.dad/file/XydPy58onY",
  "": "https://gdflix-dad.cdn.ampproject.org/c/s/gdflix.dad/file/OkrFFC8kko",
  "Officer on Duty": "https://new6.gdflix.dad/file/NmQiif6NLN",
  "Mere Yaar Ki Shaadi Hai": "https://gdflix-dad.cdn.ampproject.org/c/s/gdflix.dad/file/OomqIa9WzN",
  "Lucifer": "https://new6.gdflix.dad/file/tFt8ggLunq",
  "Tumko Meri Kasam": "https://new6.gdflix.dad/file/4n2N9qHJRT",
  "Wolf King": "https://gdflix-dad.cdn.ampproject.org/c/s/gdflix.dad/file/qAH7lf6YJF",
  "Shang-Chi and the Legend of the Ten Rings": "https://gdflix-dad.cdn.ampproject.org/c/s/gdflix.dad/file/dQkuE3f9vp",
  "Sathamanam Bhavati – S/O Krishnamurthy": "https://new6.gdflix.dad/file/CaTAbjUEsD",
  "Iratta": "https://gdflix-dad.cdn.ampproject.org/c/s/gdflix.dad/file/HfkfVy4Gz5",
  "Bhairava Geetha": "https://new6.gdflix.dad/file/xd4EBW4Z6r",
  "The Tourist": "https://gdflix-dad.cdn.ampproject.org/c/s/gdflix.dad/file/AJ3ZJ8ox8a",
  "Batman Ninja vs. Yakuza League": "https://gdflix-dad.cdn.ampproject.org/c/s/gdflix.dad/file/V6a6kk0TXt",
  "Tyler Perry’s Duplicity": "https://new6.gdflix.dad/file/h9Wl4jabN8",
  "The Twister: Caught in the Storm": "https://gdflix-dad.cdn.ampproject.org/c/s/gdflix.dad/file/csUx94cOER",
  "Blue Beetle": "https://new6.gdflix.dad/file/xSzBcXxhxo",
  "IIFA Awards": "https://new6.gdflix.dad/file/7VadjIKzIe",
  "Skip a Beat": "https://new6.gdflix.dad/file/M3kO6RQi06",
  "[18+] Yoasobi Gurashi!": "https://gdflix-dad.cdn.ampproject.org/c/s/gdflix.dad/file/Je5806lDF1",
  "The Negotiation": "https://gdflix-dad.cdn.ampproject.org/c/s/gdflix.dad/file/XpRAgGTNvU",
  "Madame Antoine: The Love Therapist": "https://new6.gdflix.dad/file/R6y7gN5UHF",
  "Smile to Life": "https://new6.gdflix.dad/file/reYLRfEmLJ",
  "Mithde": "https://gdflix-dad.cdn.ampproject.org/c/s/gdflix.dad/file/zOl00SMh1U",
  "[18+] Chidiya": "https://gdflix-dad.cdn.ampproject.org/c/s/gdflix.dad/file/Cc7JLfZ0ka",
  "Lake Consequence": "https://gdflix-dad.cdn.ampproject.org/c/s/gdflix.dad/file/jVNJByhuOk",
  "The Shallows": "https://gdflix-dad.cdn.ampproject.org/c/s/gdflix.dad/file/EL0RNngHfy",
  "Hitch": "https://new6.gdflix.dad/file/6xLg0VnN14",
  "Ek Radha Ek Meera": "https://new6.gdflix.dad/file/eJBxIjFkam",
  "Khadaan": "https://new6.gdflix.dad/file/2t3ji7ULL3",
  "Sabdham": "https://new6.gdflix.dad/file/Vbwz850x6Y",
  "The Electric State": "https://new6.gdflix.dad/file/Iga0vHJuNs",
  "The Good Boss": "https://new6.gdflix.dad/file/SyNhVowFRs",
  "Riwaj": "https://new6.gdflix.dad/file/1PSKgEmRzX",
  "Monsoon Shootout": "https://new6.gdflix.dad/file/OEQNyyGAIr",
  "Uppena": "https://new6.gdflix.dad/file/0Mz2jXVua8",
  "Zee Rishtey Awards": "https://new6.gdflix.dad/file/iLXeO0sSyJ",
  "Samrenu": "https://gdflix-dad.cdn.ampproject.org/c/s/gdflix.dad/file/3iDb3O96lQ",
  "Lucknow Central": "https://gdflix-dad.cdn.ampproject.org/c/s/gdflix.dad/file/yy3tmXkYEm",
  "Meri Pyaari Bindu": "https://new6.gdflix.dad/file/AY81srRnXn",
  "Mirza Juuliet": "https://new6.gdflix.dad/file/wOmnQBon4Y",
  "Mickey 17": "https://new6.gdflix.dad/file/K3ixhKmm9g",
  "Sharato Lagu": "https://new6.gdflix.dad/file/ThZDkRtbkf",
  "Tere Naal Love Ho Gaya": "https://new6.gdflix.dad/file/Nj9bR1HSlV",
  "Tamburo": "https://new6.gdflix.dad/file/OdNNPjz9fG",
  "The King’s Man": "https://gdflix-dad.cdn.ampproject.org/c/s/gdflix.dad/file/dbx7NFPdph",
  "Manje Bistre 2": "https://new6.gdflix.dad/file/A7e920T6G1",
  "Kingsman: The Golden Circle": "https://new6.gdflix.dad/file/hfZD4EVVsG",
  "Manje Bistre": "https://gdflix-dad.cdn.ampproject.org/c/s/gdflix.dad/file/q7XB5FVZ7D",
  "Kingsman: The Secret Service": "https://new6.gdflix.dad/file/1XqUghDYNJ",
  "The 4th Floor": "https://gdflix-dad.cdn.ampproject.org/c/s/gdflix.dad/file/jw37hAIjYt",
  "Lovelace": "https://new6.gdflix.dad/file/7TQRaIZbDr",
  "The Trial – Pyaar, Kaanoon, Dhokha": "https://new6.gdflix.dad/file/EhylvM64iD",
  "Ace Ventura: When Nature Calls": "https://gdflix-dad.cdn.ampproject.org/c/s/gdflix.dad/file/rqY3lPJkAv",
  "Ape vs. Monster": "https://new6.gdflix.dad/file/hJ28WZDh8n",
  "Loot Kaand": "https://new6.gdflix.dad/file/lNES24XWoJ",
  "Swag": "https://new6.gdflix.dad/file/vNlrI8qU0H",
  "Vanvaas": "https://new6.gdflix.dad/file/UJmnrsaJoy",
  "Be Happy": "https://new6.gdflix.dad/file/vg7N7DFBrh",
  "Assassin’s Guild": "https://new6.gdflix.dad/file/6tuvqAOuSi",
  "Hal Bheru Gamde": "https://gdflix-dad.cdn.ampproject.org/c/s/gdflix.dad/file/fl941vQO21",
  "[18+] Taisho Era Contract Marriage ~ The Substitute Bride and a Soldier’s Fierce Love": "https://gdflix-dad.cdn.ampproject.org/c/s/gdflix.dad/file/2O9Q9BAP6h",
  "[18+] Adam’s Sweet Agony": "https://gdflix-dad.cdn.ampproject.org/c/s/gdflix.dad/file/KIEp2dBASt",
};

export default movieDownloadLinks;
