name: Run Movie Scraper

on:
  schedule:
    - cron: '0 3 * * 1'  # Every Monday at 3:00 AM UTC
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install -y ./google-chrome-stable_current_amd64.deb

    - name: Install Chrome dependencies
      run: |
        sudo apt-get install -y \
          libnss3 \
          libxss1 \
          libasound2t64 \
          libxcomposite1 \
          libxcursor1 \
          libxdamage1 \
          libxi6 \
          libxtst6 \
          libatk1.0-0 \
          libatk-bridge2.0-0 \
          libcups2 \
          libdrm2 \
          libgbm1 \
          libgtk-3-0 \
          libxrandr2 \
          libxinerama1 \
          libpango-1.0-0 \
          libappindicator3-1 \
          fonts-liberation \
          xdg-utils

    - name: Install ChromeDriver
      run: |
        CHROME_VERSION=$(google-chrome --version | grep -oP "\d+\.\d+\.\d+")
        CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
        wget -q "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/
        chromedriver --version

    - name: Install missing dependencies
      run: |
        sudo apt-get install -y \
          libnss3 \
          libxss1 \
          libappindicator1 \
          libindicator7 \
          libgbm-dev \
          fonts-liberation \
          libasound2 \
          xdg-utils \
          libu2f-udev \
          libvulkan1 \
          libdrm2 \
          libxcomposite1 \
          libxrandr2

    - name: Debug env
      run: |
        google-chrome --version
        chromedriver --version
        which google-chrome
        which chromedriver

    - name: Run Python scraper with xvfb
      run: |
        xvfb-run --auto-servernum --server-args='-screen 0 1920x1080x24' python3 mkvcinemas_scrapper.py

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Auto update movie links" || echo "No changes to commit"
        git push
