name: Run Movie Scraper

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:

jobs:
  scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t scraper .

      - name: Run scraper inside Docker
        run: docker run --rm -v ${{ github.workspace }}:/app scraper

      - name: Show Git Diff (Debug)
        run: git diff

      - name: Commit & Push changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${GITHUB_REPOSITORY}
          
          # Fetch and merge the remote changes
          git fetch origin
          git merge origin/main --strategy=recursive --strategy-option=theirs
          
          git add .
          git commit -m "Auto-update download links" || echo "No changes to commit"
          git push